package br.gov.mt.mti.fiplangrf.web.security.authentication.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-08-30T13:42:40.129-04:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "LoginWS", name = "fiplan-grpPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface FiplanGrpPortType {

    @WebMethod
    @RequestWrapper(localName = "autenticar", targetNamespace = "LoginWS", className = "br.gov.mt.cepromat.fiplangnf.web.security.authentication.service.Autenticar")
    @ResponseWrapper(localName = "autenticarResponse", targetNamespace = "LoginWS", className = "br.gov.mt.cepromat.fiplangnf.web.security.authentication.service.AutenticarResponse")
    @WebResult(name = "out", targetNamespace = "LoginWS")
    public BeanWebService autenticar(
        @WebParam(name = "cpf", targetNamespace = "LoginWS")
        java.lang.String cpf,
        @WebParam(name = "senha", targetNamespace = "LoginWS")
        java.lang.String senha
    );
}
