package br.gov.mt.mti.fiplangrf.web.security.authentication.service;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-08-30T13:42:40.198-04:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "fiplan-grp",                   
                  targetNamespace = "LoginWS") 
public class FiplanGrp extends Service {

    public final static URL WSDL_LOCATION = null;

    public final static QName SERVICE = new QName("LoginWS", "fiplan-grp");
    public final static QName FiplanGrpHttpPort = new QName("LoginWS", "fiplan-grpHttpPort");

    public FiplanGrp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FiplanGrp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FiplanGrp() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FiplanGrp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FiplanGrp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FiplanGrp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns FiplanGrpPortType
     */
    @WebEndpoint(name = "fiplan-grpHttpPort")
    public FiplanGrpPortType getFiplanGrpHttpPort() {
        return super.getPort(FiplanGrpHttpPort, FiplanGrpPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FiplanGrpPortType
     */
    @WebEndpoint(name = "fiplan-grpHttpPort")
    public FiplanGrpPortType getFiplanGrpHttpPort(WebServiceFeature... features) {
        return super.getPort(FiplanGrpHttpPort, FiplanGrpPortType.class, features);
    }

}
