--------------------------------------------------------
--  DDL for Table DHWTB018_USUARIO
--------------------------------------------------------
CREATE SEQUENCE DHWSQ018_USUARIO NOCACHE;

CREATE TABLE DHWTB018_USUARIO
(	
	IDEN_USUARIO NUMBER(19), 
	VERSAO NUMBER(19), 
	NUMR_CPF VARCHAR2(14), 
	DATA_ULTIMO_ACESSO TIMESTAMP(6), 
	FOTO_PERFIL BLOB, 
	FLAG_SITUACAO VARCHAR2(7),
	DATA_CRIACAO DATE, --Obrigatorio,
  	DATA_ATUALIZACAO DATE, --Obrigatorio
  	CONSTRAINT DHWPK018_USUARIO PRIMARY KEY (IDEN_USUARIO)
);

CREATE TABLE DHWTB018_USUARIO_AUD 
(	
	IDEN_USUARIO NUMBER(19), 
	NUMR_CPF VARCHAR2(14), 
	DATA_ULTIMO_ACESSO TIMESTAMP(6), 
	FOTO_PERFIL BLOB, 
	SESSION_ID VARCHAR2(400), 
	FLAG_SITUACAO VARCHAR2(7) DEFAULT 'ATIVO',
	TIPO_OPERACAO NUMBER(3), --Obrigatorio
  	IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

--------------------------------------------------------
--DDL FOR TABLE DHWTB020_ARQUIVO_ANEXO
--------------------------------------------------------
CREATE SEQUENCE DHWSQ020_ARQUIVO_ANEXO NOCACHE;

CREATE TABLE DHWTB020_ARQUIVO_ANEXO
(
  IDEN_ARQUIVO_ANEXO NUMBER(8) NOT NULL,
  BLOB_ARQUIVO_ANEXO BLOB NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK020_ARQUIVO_ANEXO PRIMARY KEY (IDEN_ARQUIVO_ANEXO)
);

--------------------------------------------------------
--DDL FOR TABLE DHWTB019_ANEXO
--------------------------------------------------------
CREATE SEQUENCE DHWSQ019_ANEXO NOCACHE;

CREATE TABLE DHWTB019_ANEXO
(
  IDEN_ANEXO NUMBER(8) NOT NULL,
  DESC_ARQUIVO_ANEXO VARCHAR(2000) NOT NULL,
  QTDE_BYTES NUMBER(13) NOT NULL,
  DESC_CONTENT_TYPE VARCHAR2(100) NOT NULL,
  IDEN_ARQUIVO_ANEXO NUMBER(8) NOT NULL,
  IDEN_USUARIO NUMBER(8) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK019_ANEXO PRIMARY KEY (IDEN_ANEXO),
  CONSTRAINT DHWFK019_DHWTB020_ARQUIVO_ANEX FOREIGN KEY (IDEN_ARQUIVO_ANEXO) REFERENCES DHWTB020_ARQUIVO_ANEXO(IDEN_ARQUIVO_ANEXO),
  CONSTRAINT DHWFK019_DHWTB018_USUARIO FOREIGN KEY (IDEN_USUARIO) REFERENCES DHWTB018_USUARIO(IDEN_USUARIO)
);

CREATE TABLE DHWTB019_ANEXO_AUD 
(
  IDEN_ANEXO NUMBER(8) NOT NULL,
  DESC_ARQUIVO_ANEXO VARCHAR(2000) NOT NULL,
  QTDE_BYTES NUMBER(13) NOT NULL,
  DESC_CONTENT_TYPE VARCHAR2(100) NOT NULL,
  IDEN_USUARIO NUMBER(8) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

commit;
--------------------------------------------------------
--  DDL FOR TABLE DHWTB001_TIPO_OCORRENCIA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ001_TIPO_OCORRENCIA NOCACHE;

CREATE TABLE DHWTB001_TIPO_OCORRENCIA 
(
  IDEN_TIPO_OCORRENCIA NUMBER(8) NOT NULL, 
  DESC_TIPO_OCORRENCIA VARCHAR2(100) NOT NULL, 
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK001_TIPO_OCORRENCIA PRIMARY KEY (IDEN_TIPO_OCORRENCIA)
);

CREATE TABLE DHWTB001_TIPO_OCORRENCIA_AUD 
(
  IDEN_TIPO_OCORRENCIA NUMBER(8) NOT NULL, 
  DESC_TIPO_OCORRENCIA VARCHAR2(100) NOT NULL, 
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL --Obrigatorio
);

commit;
--------------------------------------------------------
--  DDL FOR TABLE DHWTB002_GRUPO_PENDENCIA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ002_GRUPO_PENDENCIA NOCACHE;

CREATE TABLE DHWTB002_GRUPO_PENDENCIA 
(
  IDEN_GRUPO_PENDENCIA NUMBER(8) NOT NULL, 
  DESC_GRUPO_PENDENCIA VARCHAR2(200) NOT NULL, 
  IDEN_TIPO_OCORRENCIA NUMBER(8) NOT NULL,
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK002_GRUPO_PENDENCIA PRIMARY KEY (IDEN_GRUPO_PENDENCIA),
  CONSTRAINT DHWFK002_DHWTB001_TIPO_OCORREN FOREIGN KEY (IDEN_TIPO_OCORRENCIA) REFERENCES DHWTB001_TIPO_OCORRENCIA(IDEN_TIPO_OCORRENCIA)
);

CREATE TABLE DHWTB002_GRUPO_PENDENCIA_AUD 
(
  IDEN_GRUPO_PENDENCIA NUMBER(8) NOT NULL, 
  DESC_GRUPO_PENDENCIA VARCHAR2(200) NOT NULL,
  IDEN_TIPO_OCORRENCIA NUMBER(8) NOT NULL,
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

commit;
--------------------------------------------------------
--  DDL FOR TABLE DHWTB003_SUBGRUPO_PENDENCIA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ003_SUBGRUPO_PENDENCIA NOCACHE;

CREATE TABLE DHWTB003_SUBGRUPO_PENDENCIA 
(
  IDEN_SUBGRUPO_PENDENCIA NUMBER(8) NOT NULL, 
  DESC_SUBGRUPO_PENDENCIA VARCHAR2(200) NOT NULL, 
  IDEN_GRUPO_PENDENCIA NUMBER(8) NOT NULL,
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK003_SUBGRUPO_PENDENCIA PRIMARY KEY (IDEN_SUBGRUPO_PENDENCIA),
  CONSTRAINT DHWFK003_DHWTB002_GRUPO_PENDEN FOREIGN KEY (IDEN_GRUPO_PENDENCIA) REFERENCES DHWTB002_GRUPO_PENDENCIA(IDEN_GRUPO_PENDENCIA)
);

CREATE TABLE DHWTB003_SUBGRUPO_PEND_AUD 
(
  IDEN_SUBGRUPO_PENDENCIA NUMBER(8) NOT NULL, 
  DESC_SUBGRUPO_PENDENCIA VARCHAR2(200) NOT NULL,
  IDEN_GRUPO_PENDENCIA NUMBER(8) NOT NULL,
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

commit;
--------------------------------------------------------
--  DDL FOR TABLE DHWTB004_TIPO_PENDENCIA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ004_TIPO_PENDENCIA NOCACHE;

CREATE TABLE DHWTB004_TIPO_PENDENCIA 
(
  IDEN_TIPO_PENDENCIA NUMBER(8) NOT NULL,
  SIGLA_TIPO_PENDENCIA VARCHAR2(100) NOT NULL,
  DESC_TIPO_PENDENCIA VARCHAR2(200) NOT NULL, 
  IDEN_TIPO_OCORRENCIA NUMBER(8) NOT NULL,
  IDEN_GRUPO_PENDENCIA NUMBER(8),
  IDEN_SUBGRUPO_PENDENCIA NUMBER(8),
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK004_TIPO_PENDENCIA PRIMARY KEY (IDEN_TIPO_PENDENCIA),
  CONSTRAINT DHWFK004_DHWTB001_TIPO_OCORREN FOREIGN KEY (IDEN_TIPO_OCORRENCIA) REFERENCES DHWTB001_TIPO_OCORRENCIA(IDEN_TIPO_OCORRENCIA),
  CONSTRAINT DHWFK004_DHWTB002_GRUPO_PENDEN FOREIGN KEY (IDEN_GRUPO_PENDENCIA) REFERENCES DHWTB002_GRUPO_PENDENCIA(IDEN_GRUPO_PENDENCIA),
  CONSTRAINT DHWFK004_DHWTB003_SUBGRUPO_PEN FOREIGN KEY (IDEN_SUBGRUPO_PENDENCIA) REFERENCES DHWTB003_SUBGRUPO_PENDENCIA(IDEN_SUBGRUPO_PENDENCIA)
);

CREATE TABLE DHWTB004_TIPO_PENDENCIA_AUD 
(
  IDEN_TIPO_PENDENCIA NUMBER(8) NOT NULL, 
  SIGLA_TIPO_PENDENCIA VARCHAR2(100) NOT NULL, 
  DESC_TIPO_PENDENCIA VARCHAR2(200) NOT NULL, 
  IDEN_TIPO_OCORRENCIA NUMBER(8) NOT NULL,
  IDEN_GRUPO_PENDENCIA NUMBER(8),
  IDEN_SUBGRUPO_PENDENCIA NUMBER(8),
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

commit;
--------------------------------------------------------
--  DDL FOR TABLE DHWTB005_TIPO_ADMINISTRACAO
--------------------------------------------------------
CREATE SEQUENCE DHWSQ005_TIPO_ADMINISTRACAO NOCACHE;

CREATE TABLE DHWTB005_TIPO_ADMINISTRACAO 
(
  IDEN_TIPO_ADMINISTRACAO NUMBER(8) NOT NULL, 
  DESC_TIPO_ADMINISTRACAO VARCHAR2(200) NOT NULL, 
  FLAG_TIPO_PODER VARCHAR2(50) NOT NULL,
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK005_TIPO_ADMINISTRACAO PRIMARY KEY (IDEN_TIPO_ADMINISTRACAO)
);

CREATE TABLE DHWTB005_TIPO_ADM_AUD 
(
  IDEN_TIPO_ADMINISTRACAO NUMBER(8) NOT NULL, 
  DESC_TIPO_ADMINISTRACAO VARCHAR2(200) NOT NULL,
  FLAG_TIPO_PODER VARCHAR2(50) NOT NULL,
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

commit;
--------------------------------------------------------
--  DDL FOR TABLE DHWTB006_NATUREZA_JURIDICA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ006_NATUREZA_JURIDICA NOCACHE;

CREATE TABLE DHWTB006_NATUREZA_JURIDICA 
(
  IDEN_NATUREZA_JURIDICA NUMBER(8) NOT NULL, 
  NUMR_NATUREZA_JURIDICA NUMBER(5) NOT NULL, 
  DESC_NATUREZA_JURIDICA VARCHAR2(200) NOT NULL, 
  FLAG_TIPO_NATUREZA_JURIDICA VARCHAR2(100) NOT NULL, 
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK006_NATUREZA_JURIDICA PRIMARY KEY (IDEN_NATUREZA_JURIDICA)
);

CREATE TABLE DHWTB006_NATUREZA_JURIDICA_AUD 
(
  IDEN_NATUREZA_JURIDICA NUMBER(8) NOT NULL, 
  NUMR_NATUREZA_JURIDICA NUMBER(5) NOT NULL, 
  DESC_NATUREZA_JURIDICA VARCHAR2(200) NOT NULL, 
  FLAG_TIPO_NATUREZA_JURIDICA VARCHAR2(100) NOT NULL, 
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

commit;
--------------------------------------------------------
--  DDL FOR TABLE DHWTB007_CNAE
--------------------------------------------------------
CREATE SEQUENCE DHWSQ007_CNAE NOCACHE;
   
CREATE TABLE DHWTB007_CNAE (    
    IDEN_CNAE NUMBER(8) NOT NULL,
    NUMR_CNAE NUMBER(7) NOT NULL,
    DESC_CNAE VARCHAR2(200) NOT NULL, 
    FLAG_SITUACAO VARCHAR2(7) NOT NULL,
    DATA_CRIACAO DATE, --Obrigatorio
	DATA_ATUALIZACAO DATE, --Obrigatorio
	CONSTRAINT DHWPK007_CNAE PRIMARY KEY (IDEN_CNAE)
);
  
CREATE TABLE DHWTB007_CNAE_AUD ( 
    IDEN_CNAE NUMBER(8) NOT NULL,
    NUMR_CNAE NUMBER(7) NOT NULL,
    DESC_CNAE VARCHAR2(200) NOT NULL, 
    FLAG_SITUACAO VARCHAR2(7) NOT NULL,
    TIPO_OPERACAO NUMBER(3), --Obrigatorio
    IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

commit;
--------------------------------------------------------
--  DDL FOR TABLE DHWTB008_UND_ADMINISTRATIVA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ008_UNIDADE_ADMINISTRATIV NOCACHE;

CREATE TABLE DHWTB008_UNIDADE_ADMINISTRATIV 
(
  IDEN_UNIDADE_ADMINISTRATIVA NUMBER(8) NOT NULL,
  NUMR_CNPJ NUMBER(14) NOT NULL,
  NOME_EMPRESARIAL VARCHAR2(200) NOT NULL, 
  SIGLA VARCHAR2(20) NOT NULL,
  FLAG_SITUACAO_CADASTRAL_CNPJ VARCHAR2(10) NOT NULL,
  FLAG_TIPO_PODER VARCHAR2(50) NOT NULL,
  FLAG_UND_ORCAMEN_CADAST_FIPLAN VARCHAR2(50) NOT NULL,
  IDEN_TIPO_ADMINISTRACAO NUMBER(8) NOT NULL,
  CODG_UNIDADE_ORCAMENTARIA NUMBER(8),
  SIGLA_UNIDADE_ORCAMENTARIA VARCHAR2(20),
  DESC_UNIDADE_ORCAMENTARIA VARCHAR2(100),
  NUMR_EXER_UND_ORCAMENTARIA NUMBER(8),
  DATA_ABERTURA DATE,
  DATA_TERMINO DATE,
  FLAG_TIPO_NATUREZA_JURIDICA VARCHAR2(100) NOT NULL,
  IDEN_NATUREZA_JURIDICA NUMBER(8) NOT NULL,
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK008_UND_ADMINISTRATIVA PRIMARY KEY (IDEN_UNIDADE_ADMINISTRATIVA),
  CONSTRAINT DHWFK008_DHWTB005_TIPO_ADMINIS FOREIGN KEY (IDEN_TIPO_ADMINISTRACAO) REFERENCES DHWTB005_TIPO_ADMINISTRACAO(IDEN_TIPO_ADMINISTRACAO),
  CONSTRAINT DHWFK008_DHWTB006_NATURE_JURID FOREIGN KEY (IDEN_NATUREZA_JURIDICA) REFERENCES DHWTB006_NATUREZA_JURIDICA(IDEN_NATUREZA_JURIDICA)
);

CREATE TABLE DHWTB008_UND_ADMINISTRATIV_AUD 
(
  IDEN_UNIDADE_ADMINISTRATIVA NUMBER(8) NOT NULL,
  NUMR_CNPJ NUMBER(14) NOT NULL,
  NOME_EMPRESARIAL VARCHAR2(200) NOT NULL, 
  SIGLA VARCHAR2(20) NOT NULL,
  FLAG_SITUACAO_CADASTRAL_CNPJ VARCHAR2(10) NOT NULL,
  FLAG_TIPO_PODER VARCHAR2(50) NOT NULL,
  FLAG_UND_ORCAMEN_CADAST_FIPLAN VARCHAR2(50) NOT NULL,
  IDEN_TIPO_ADMINISTRACAO NUMBER(8) NOT NULL,
  SIGLA_UNIDADE_ORCAMENTARIA VARCHAR2(20),
  CODG_UNIDADE_ORCAMENTARIA NUMBER(8),
  DESC_UNIDADE_ORCAMENTARIA VARCHAR2(100),
  NUMR_EXER_UND_ORCAMENTARIA NUMBER(8),
  DATA_ABERTURA DATE,
  DATA_TERMINO DATE,
  FLAG_TIPO_NATUREZA_JURIDICA VARCHAR2(100) NOT NULL,
  IDEN_NATUREZA_JURIDICA NUMBER(8) NOT NULL,
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

commit;
--------------------------------------------------------
--  DDL FOR TABLE DHWTB009_CNAE_UND_ADMIN
--------------------------------------------------------
CREATE SEQUENCE DHWSQ009_CNAE_UND_ADMINISTRATI NOCACHE;

CREATE TABLE DHWTB009_CNAE_UND_ADMINISTRATI 
(	
    IDEN_CNAE_UND_ADMINSTRATIVA NUMBER(8) NOT NULL, 
    NUMR_CNAE NUMBER(7) NOT NULL, 
	DESC_ATIVIDADE VARCHAR2(200) NOT NULL, 
	FLAG_TIPO_ATIVIDADE VARCHAR2(10) NOT NULL, 
	FLAG_SITUACAO VARCHAR2(7) NOT NULL, 
	IDEN_UNIDADE_ADMINISTRATIVA NUMBER(8) NOT NULL, 
	IDEN_CNAE NUMBER(8),
    DATA_CRIACAO DATE, --Obrigatorio,
    DATA_ATUALIZACAO DATE, --Obrigatorio
    CONSTRAINT DHWPK009_CNAE_UND_ADMINISTRATI PRIMARY KEY (IDEN_CNAE_UND_ADMINSTRATIVA),
    CONSTRAINT DHWFK009_DHWTB008_UND_ADMINIST FOREIGN KEY (IDEN_UNIDADE_ADMINISTRATIVA) REFERENCES DHWTB008_UNIDADE_ADMINISTRATIV(IDEN_UNIDADE_ADMINISTRATIVA),
    CONSTRAINT DHWFK009_DHWTB007_CNAE FOREIGN KEY (IDEN_CNAE) REFERENCES DHWTB007_CNAE(IDEN_CNAE)
);

CREATE TABLE DHWTB009_CNAE_UND_ADMIN_AUD
(	IDEN_CNAE_UND_ADMINSTRATIVA NUMBER(8), 
	NUMR_CNAE NUMBER(7), 
	DESC_ATIVIDADE VARCHAR2(200), 
	FLAG_TIPO_ATIVIDADE VARCHAR2(10), 
	FLAG_SITUACAO VARCHAR2(7), 
	DATA_CRIACAO DATE, 
	DATA_ATUALIZACAO DATE, 
	IDEN_UNIDADE_ADMINISTRATIVA NUMBER(8), 
	IDEN_CNAE NUMBER(8), 
	TIPO_OPERACAO NUMBER(3), --Obrigatorio
    IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);
commit;

--------------------------------------------------------
--  DDL FOR TABLE DHWTB010_LEGISLACAO_UND_ADMINI
--------------------------------------------------------
CREATE SEQUENCE DHWSQ010_LEGISLACAO_UND_ADMINI NOCACHE;
   
CREATE TABLE DHWTB010_LEGISLACAO_UND_ADMINI (    
    IDEN_LEGISLACAO_UND_ADM NUMBER(8) NOT NULL,
    TIPO_LEGISLACAO VARCHAR(20) NOT NULL,
    DESC_LEI VARCHAR2(200) NOT NULL, 
    FLAG_SITUACAO VARCHAR2(7) NOT NULL,  
    IDEN_UNIDADE_ADMINISTRATIVA NUMBER(8),
    DATA_CRIACAO DATE, --Obrigatorio
	DATA_ATUALIZACAO DATE, --Obrigatorio
	CONSTRAINT DHWPK010_LEGISLA_UND_ADMINISTR PRIMARY KEY (IDEN_LEGISLACAO_UND_ADM),
	CONSTRAINT DHWFK010_DHWTB008_UND_ADMINIST FOREIGN KEY (IDEN_UNIDADE_ADMINISTRATIVA) REFERENCES DHWTB008_UNIDADE_ADMINISTRATIV(IDEN_UNIDADE_ADMINISTRATIVA)
	
);
  
CREATE TABLE DHWTB010_LEG_UND_ADM_AUD ( 
    IDEN_LEGISLACAO_UND_ADM NUMBER(8) NOT NULL,
    TIPO_LEGISLACAO VARCHAR(20) NOT NULL,
    DESC_LEI VARCHAR2(200) NOT NULL, 
    FLAG_SITUACAO VARCHAR2(7) NOT NULL,
    IDEN_UNIDADE_ADMINISTRATIVA NUMBER(8),
    TIPO_OPERACAO NUMBER(3), --Obrigatorio
    IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

--------------------------------------------------------
--  DDL FOR TABLE DHWSQ011_OCORRENCIA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ011_OCORRENCIA NOCACHE;

CREATE TABLE DHWTB011_OCORRENCIA
(
  IDEN_OCORRENCIA NUMBER(8) NOT NULL,
  IDEN_UNIDADE_ADMINISTRATIVA NUMBER(14) NOT NULL,
  CODG_UNIDADE_ORCAMENTARIA NUMBER(8),
  DESC_UNIDADE_ORCAMENTARIA VARCHAR(100),
  SIGLA_UNIDADE_ORCAMENTARIA VARCHAR(20),
  NUMR_EXER_UND_ORCAMENTARIA VARCHAR2(4),
  IDEN_TIPO_OCORRENCIA NUMBER(8) NOT NULL,
  IDEN_GRUPO_PENDENCIA NUMBER(8),
  IDEN_SUBGRUPO_PENDENCIA NUMBER(8),
  IDEN_TIPO_PENDENCIA NUMBER(8),
  DATA_INSCRICAO DATE NOT NULL,
  FLAG_SITUACAO_PENDENCIA VARCHAR2(20) NOT NULL,
  DATA_REGULARIZACAO DATE,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK011_OCORRENCIA PRIMARY KEY (IDEN_OCORRENCIA),
  CONSTRAINT DHWFK011_DHWTB008_UND_ADMINIST FOREIGN KEY (IDEN_UNIDADE_ADMINISTRATIVA) REFERENCES DHWTB008_UNIDADE_ADMINISTRATIV(IDEN_UNIDADE_ADMINISTRATIVA),
  CONSTRAINT DHWFK011_DHWTB001_TIPO_OCORREN FOREIGN KEY (IDEN_TIPO_OCORRENCIA) REFERENCES DHWTB001_TIPO_OCORRENCIA(IDEN_TIPO_OCORRENCIA),
  CONSTRAINT DHWFK011_DHWTB002_GRUPO_PENDEN FOREIGN KEY (IDEN_GRUPO_PENDENCIA) REFERENCES DHWTB002_GRUPO_PENDENCIA(IDEN_GRUPO_PENDENCIA),
  CONSTRAINT DHWFK011_DHWTB003_SUBGRU_PENDE FOREIGN KEY (IDEN_SUBGRUPO_PENDENCIA) REFERENCES DHWTB003_SUBGRUPO_PENDENCIA(IDEN_SUBGRUPO_PENDENCIA),
  CONSTRAINT DHWFK011_DHWTB004_TIPO_PENDENC FOREIGN KEY (IDEN_TIPO_PENDENCIA) REFERENCES DHWTB004_TIPO_PENDENCIA(IDEN_TIPO_PENDENCIA)
);

CREATE TABLE DHWTB011_OCORRENCIA_AUD 
(
  IDEN_OCORRENCIA NUMBER(8) NOT NULL,
  IDEN_UNIDADE_ADMINISTRATIVA NUMBER(14) NOT NULL,
  CODG_UNIDADE_ORCAMENTARIA NUMBER(8),
  DESC_UNIDADE_ORCAMENTARIA VARCHAR(100),
  SIGLA_UNIDADE_ORCAMENTARIA VARCHAR(20),
  NUMR_EXER_UND_ORCAMENTARIA VARCHAR2(4),
  IDEN_TIPO_OCORRENCIA NUMBER(8) NOT NULL,
  IDEN_GRUPO_PENDENCIA NUMBER(8),
  IDEN_SUBGRUPO_PENDENCIA VARCHAR2(8),
  IDEN_TIPO_PENDENCIA NUMBER(8),
  DATA_INSCRICAO DATE NOT NULL,
  FLAG_SITUACAO_PENDENCIA VARCHAR2(20) NOT NULL,
  DATA_REGULARIZACAO DATE,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

--------------------------------------------------------
--  DDL FOR TABLE DHWTB012_ACAO_COORDENADORIA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ012_ACAO_COORDENADORIA NOCACHE;

CREATE TABLE DHWTB012_ACAO_COORDENADORIA
(
  IDEN_ACAO_COORDENADORIA NUMBER(8) NOT NULL,
  DESC_ACAO_COORDENADORIA VARCHAR(2000) NOT NULL,
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  IDEN_OCORRENCIA NUMBER(8) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK012_ACAO_COORDENADORIA PRIMARY KEY (IDEN_ACAO_COORDENADORIA),
  CONSTRAINT DHWFK012_DHWTB011_OCORRENCIA FOREIGN KEY (IDEN_OCORRENCIA) REFERENCES DHWTB011_OCORRENCIA(IDEN_OCORRENCIA)
);

CREATE TABLE DHWTB012_ACAO_COORDEN_AUD 
(
  IDEN_ACAO_COORDENADORIA NUMBER(8) NOT NULL,
  DESC_ACAO_COORDENADORIA VARCHAR(2000) NOT NULL,
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  IDEN_OCORRENCIA NUMBER(8) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

CREATE TABLE DHWTB021_ACAO_COORDEN_ANEXO
(
  IDEN_ACAO_COORDENADORIA NUMBER(8) NOT NULL,
  IDEN_ANEXO NUMBER(8) NOT NULL,
  CONSTRAINT DHWPK021_ACAO_COORD_ANEXO PRIMARY KEY (IDEN_ACAO_COORDENADORIA),
  CONSTRAINT DHWFK021_DHWTB012_ACAO_COORDEN FOREIGN KEY (IDEN_ACAO_COORDENADORIA) REFERENCES DHWTB012_ACAO_COORDENADORIA(IDEN_ACAO_COORDENADORIA),
  CONSTRAINT DHWFK021_DHWTB019_ANEXO FOREIGN KEY (IDEN_ANEXO) REFERENCES DHWTB019_ANEXO(IDEN_ANEXO)
);

--------------------------------------------------------
--  DDL FOR TABLE DHWTB013_MEDIDA_INTERMEDIARIA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ013_MEDIDA_INTERMEDIARIA NOCACHE;

CREATE TABLE DHWTB013_MEDIDA_INTERMEDIARIA
(
  IDEN_MEDIDA_INTERMEDIARIA NUMBER(8) NOT NULL,
  DESC_MEDIDA_INTERMEDIARIA VARCHAR2(2000) NOT NULL,
  NOME_RESPONSAVEL VARCHAR(50) NOT NULL,
  DESC_CARGO_FUNCAO VARCHAR(50) NOT NULL,
  NUMR_TELEFONE VARCHAR(20) NOT NULL,
  DESC_EMAIL VARCHAR(50) NOT NULL,
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  IDEN_OCORRENCIA NUMBER(8) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK013_MEDIDA_INTERMEDIARIA PRIMARY KEY (IDEN_MEDIDA_INTERMEDIARIA),
  CONSTRAINT DHWFK013_DHWTB011_OCORRENCIA FOREIGN KEY (IDEN_OCORRENCIA) REFERENCES DHWTB011_OCORRENCIA(IDEN_OCORRENCIA)
);

CREATE TABLE DHWTB013_MED_INTERMEDIARIA_AUD 
(
  IDEN_MEDIDA_INTERMEDIARIA NUMBER(8) NOT NULL,
  DESC_MEDIDA_INTERMEDIARIA VARCHAR2(2000) NOT NULL,
  NOME_RESPONSAVEL VARCHAR(50) NOT NULL,
  DESC_CARGO_FUNCAO VARCHAR(50) NOT NULL,
  NUMR_TELEFONE VARCHAR(20) NOT NULL,
  DESC_EMAIL VARCHAR(50) NOT NULL,
  FLAG_SITUACAO VARCHAR2(7) NOT NULL,
  IDEN_OCORRENCIA NUMBER(8) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

CREATE TABLE DHWTB022_MEDIDA_INTERMED_ANEXO
(
  IDEN_MEDIDA_INTERMEDIARIA NUMBER(8) NOT NULL,
  IDEN_ANEXO NUMBER(8) NOT NULL,
  CONSTRAINT DHWPK022_MEDIDA_INTERMED_ANEXO PRIMARY KEY (IDEN_MEDIDA_INTERMEDIARIA),
  CONSTRAINT DHWFK022_DHWTB013_MED_ITERMEDI FOREIGN KEY (IDEN_MEDIDA_INTERMEDIARIA) REFERENCES DHWTB013_MEDIDA_INTERMEDIARIA(IDEN_MEDIDA_INTERMEDIARIA),
  CONSTRAINT DHWFK022_DHWTB019_ANEXO FOREIGN KEY (IDEN_ANEXO) REFERENCES DHWTB019_ANEXO(IDEN_ANEXO)
);

--------------------------------------------------------
--  DDL FOR TABLE DHWTB014_ENC_PENDENCIA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ014_ENCERRAMENTO_PENDENCI NOCACHE;

CREATE TABLE DHWTB014_ENCERRAMENTO_PENDENCI
(
  IDEN_ENCERRAMENTO_PENDENCIA NUMBER(8) NOT NULL,
  DESC_ENCERRAMENTO_PENDENCIA VARCHAR(2000) NOT NULL,
  FLAG_SITUACAO VARCHAR(7) NOT NULL,
  IDEN_OCORRENCIA NUMBER(8) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK014_ENC_PENDENCIA PRIMARY KEY (IDEN_ENCERRAMENTO_PENDENCIA),
  CONSTRAINT DHWFK014_DHWTB011_OCORRENCIA FOREIGN KEY (IDEN_OCORRENCIA) REFERENCES DHWTB011_OCORRENCIA(IDEN_OCORRENCIA)
);

CREATE TABLE DHWTB014_ENC_PENDENCIA_AUD 
(
  IDEN_ENCERRAMENTO_PENDENCIA NUMBER(8) NOT NULL,
  DESC_ENCERRAMENTO_PENDENCIA VARCHAR(2000) NOT NULL,
  FLAG_SITUACAO VARCHAR(7) NOT NULL,
  IDEN_OCORRENCIA NUMBER(8) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

CREATE TABLE DHWTB023_ENCERRAMEN_PEND_ANEXO
(
  IDEN_ENCERRAMENTO_PENDENCIA NUMBER(8) NOT NULL,
  IDEN_ANEXO NUMBER(8) NOT NULL,
  CONSTRAINT DHWPK023_ENCERRAM_PENDEN_ANEXO PRIMARY KEY (IDEN_ENCERRAMENTO_PENDENCIA),
  CONSTRAINT DHWFK023_DHWTB014_ENCER_PENDEN FOREIGN KEY (IDEN_ENCERRAMENTO_PENDENCIA) REFERENCES DHWTB014_ENCERRAMENTO_PENDENCI(IDEN_ENCERRAMENTO_PENDENCIA),
  CONSTRAINT DHWFK023_DHWTB019_ANEXO FOREIGN KEY (IDEN_ANEXO) REFERENCES DHWTB019_ANEXO(IDEN_ANEXO)
);

--------------------------------------------------------
--  DDL FOR TABLE DHWTB015_TRAMITE_OCORRENCIA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ015_TRAMITE_OCORRENCIA NOCACHE;

CREATE TABLE DHWTB015_TRAMITE_OCORRENCIA
(
  IDEN_TRAMITE_OCORRENCIA NUMBER(8) NOT NULL,
  DATA_HORA TIMESTAMP(6) NOT NULL,
  FLAG_SITUACAO_PENDENCIA VARCHAR2(20) NOT NULL,
  DESC_JUSTIFICATIVA VARCHAR(2000) ,
  IDEN_OCORRENCIA NUMBER(8) NOT NULL,
  IDEN_USUARIO NUMBER(8) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK015_TRAMITE_OCORRENCIA PRIMARY KEY (IDEN_TRAMITE_OCORRENCIA),
  CONSTRAINT DHWFK015_DHWTB011_OCORRENCIA FOREIGN KEY (IDEN_OCORRENCIA) REFERENCES DHWTB011_OCORRENCIA(IDEN_OCORRENCIA),
  CONSTRAINT DHWFK015_DHWTB018_USUARIO FOREIGN KEY (IDEN_USUARIO) REFERENCES DHWTB018_USUARIO(IDEN_USUARIO)
);

CREATE TABLE DHWTB015_TRAM_OCORRENCIA_AUD 
(
  IDEN_TRAMITE_OCORRENCIA NUMBER(8) NOT NULL,
  DATA_HORA TIMESTAMP(6) NOT NULL,
  FLAG_SITUACAO_PENDENCIA VARCHAR2(20) NOT NULL,
  DESC_JUSTIFICATIVA VARCHAR(2000) ,
  IDEN_OCORRENCIA NUMBER(8) NOT NULL,
  IDEN_USUARIO NUMBER(8) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

--------------------------------------------------------
--  DDL FOR TABLE DHWTB016_REVISAO_OCORRENCIA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ016_REVISAO_OCORRENCIA NOCACHE;

CREATE TABLE DHWTB016_REVISAO_OCORRENCIA
(
  IDEN_REVISAO_OCORRENCIA NUMBER(8) NOT NULL,
  DATA_REVISAO TIMESTAMP(6) NOT NULL,
  IDEN_USUARIO NUMBER(9) NOT NULL,
  NUMR_IP VARCHAR2(39) NOT NULL,
  DATA_CRIACAO DATE, --Obrigatorio,
  DATA_ATUALIZACAO DATE, --Obrigatorio
  CONSTRAINT DHWPK016_REVISAO_OCORRENCIA PRIMARY KEY (IDEN_REVISAO_OCORRENCIA),
  CONSTRAINT DHWFK016_DHWTB0018_USUARIO FOREIGN KEY (IDEN_USUARIO) REFERENCES DHWTB018_USUARIO(IDEN_USUARIO)
);

CREATE TABLE DHWTB016_REV_OCORRENCIA_AUD 
(
  IDEN_REVISAO_OCORRENCIA NUMBER(8) NOT NULL,
  DATA_REVISAO TIMESTAMP(6) NOT NULL,
  IDEN_USUARIO NUMBER(8) NOT NULL,
  NUMR_IP VARCHAR2(39) NOT NULL,
  TIPO_OPERACAO NUMBER(3), --Obrigatorio
  IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

--------------------------------------------------------
--  DDL FOR TABLE DHWTB017_PERFIL_ACESSO
--------------------------------------------------------
CREATE SEQUENCE DHWSQ017_PERFIL_ACESSO NOCACHE;

CREATE TABLE DHWTB017_PERFIL_ACESSO 
(
	IDEN_PERFIL_ACESSO NUMBER(19),
	VERSAO NUMBER(19), 
	DESCRICAO VARCHAR2(400), 
	FLAG_SITUACAO VARCHAR2(7), 
	NOME VARCHAR2(200),
	DATA_CRIACAO DATE, --Obrigatorio,
  	DATA_ATUALIZACAO DATE, --Obrigatorio
  	CONSTRAINT DHWPK017_PERFIL_ACESSO PRIMARY KEY (IDEN_PERFIL_ACESSO)
);

CREATE TABLE DHWTB017_PERFIL_ACESSO_AUD 
(	IDEN_PERFIL_ACESSO NUMBER(19),
	DESCRICAO VARCHAR2(400), 
	FLAG_SITUACAO VARCHAR2(7), 
	NOME VARCHAR2(200),
	TIPO_OPERACAO NUMBER(3), --Obrigatorio
  	IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

--------------------------------------------------------
--  DDL for Table DHWTB025_USUARIO_PERFIL
--------------------------------------------------------
CREATE TABLE DHWTB025_USUARIO_PERFIL
(	IDEN_USUARIO NUMBER(19), 
	IDEN_PERFIL_ACESSO NUMBER(19),
	CONSTRAINT DHWPK025_USUARIO_PERFIL PRIMARY KEY (IDEN_USUARIO),
  	CONSTRAINT DHWFK025_DHWTB017_PERFIL_ACESS FOREIGN KEY (IDEN_PERFIL_ACESSO) REFERENCES DHWTB017_PERFIL_ACESSO(IDEN_PERFIL_ACESSO),
  	CONSTRAINT DHWFK025_DHWTB018_USUARIO FOREIGN KEY (IDEN_USUARIO) REFERENCES DHWTB018_USUARIO(IDEN_USUARIO)
);

CREATE TABLE DHWTB025_USUARIO_PERFIL_AUD
(	IDEN_USUARIO NUMBER(19), 
	IDEN_PERFIL_ACESSO NUMBER(19),
	TIPO_OPERACAO NUMBER(3), --Obrigatorio
  	IDEN_AUDITORIA NUMBER(10) NOT NULL ENABLE --Obrigatorio
);

--------------------------------------------------------
--  DDL FOR TABLE DHWTB027_FUNCIONALIDADE
--------------------------------------------------------
CREATE SEQUENCE DHWSQ027_FUNCIONALIDADE NOCACHE;

CREATE TABLE DHWTB027_FUNCIONALIDADE
(	
	IDEN_FUNCIONALIDADE NUMBER(19), 
	VERSAO NUMBER(19), 
	DESCRICAO VARCHAR2(400), 
	NOME VARCHAR2(200), 
	FLAG_SITUACAO VARCHAR2(7),
	DATA_CRIACAO DATE, --Obrigatorio,
  	DATA_ATUALIZACAO DATE, --Obrigatorio
	CONSTRAINT DHWPK024_FUNCIONALIDADE PRIMARY KEY (IDEN_FUNCIONALIDADE)
);

CREATE TABLE DHWTB027_FUNCIONALIDADE_AUD
(	
	IDEN_FUNCIONALIDADE NUMBER(19), 
	DESCRICAO VARCHAR2(400), 
	NOME VARCHAR2(200), 
	FLAG_SITUACAO VARCHAR2(7),
	TIPO_OPERACAO NUMBER(3), --Obrigatorio
  	IDEN_AUDITORIA NUMBER(10) NOT NULL --Obrigatorio
);
--------------------------------------------------------
--  DDL for Table DHWTB024_PERFIL_FUNC
--------------------------------------------------------

CREATE TABLE DHWTB024_PERFIL_FUNC
(
	IDEN_PERFIL_ACESSO NUMBER(19), 
	IDEN_FUNCIONALIDADE NUMBER(19),
	CONSTRAINT DHWPK024_PERFIL_FUNC PRIMARY KEY (IDEN_PERFIL_ACESSO,IDEN_FUNCIONALIDADE),
  	CONSTRAINT DHWFK024_DHWTB017_PERFIL_ACESS FOREIGN KEY (IDEN_PERFIL_ACESSO) REFERENCES DHWTB017_PERFIL_ACESSO(IDEN_PERFIL_ACESSO),
  	CONSTRAINT DHWFK024_DHWTB027_FUNCIONALIDA FOREIGN KEY (IDEN_FUNCIONALIDADE) REFERENCES DHWTB027_FUNCIONALIDADE(IDEN_FUNCIONALIDADE)
);

CREATE TABLE DHWTB024_PERFIL_FUNC_AUD
(
	IDEN_PERFIL_ACESSO NUMBER(19), 
	IDEN_FUNCIONALIDADE NUMBER(19),
	TIPO_OPERACAO NUMBER(3), --Obrigatorio
  	IDEN_AUDITORIA NUMBER(10) NOT NULL --Obrigatorio
);

--------------------------------------------------------
--  DDL for Table DHWTB025_PERMISSAO
--------------------------------------------------------
CREATE SEQUENCE DHWSQ028_PERMISSAO NOCACHE;

CREATE TABLE DHWTB028_PERMISSAO 
(
	IDEN_PERMISSAO NUMBER(19) NOT NULL, 
	VERSAO NUMBER(19) NOT NULL, 
	ACTION VARCHAR2(4000) NOT NULL, 
	DESCRICAO VARCHAR2(400) NOT NULL, 
	NOME VARCHAR2(200) NOT NULL, 
	TIPO_PERMISSAO VARCHAR2(255) NOT NULL,
	DATA_CRIACAO DATE, --Obrigatorio,
  	DATA_ATUALIZACAO DATE, --Obrigatorio
	CONSTRAINT DHWPK028_PERMISSAO  PRIMARY KEY (IDEN_PERMISSAO)
);

CREATE TABLE DHWTB028_PERMISSAO_AUD
(
	IDEN_PERMISSAO NUMBER(19) NOT NULL, 
	ACTION VARCHAR2(4000) NOT NULL, 
	DESCRICAO VARCHAR2(400) NOT NULL, 
	NOME VARCHAR2(200) NOT NULL, 
	TIPO_PERMISSAO VARCHAR2(255) NOT NULL,
	TIPO_OPERACAO NUMBER(3), --Obrigatorio
  	IDEN_AUDITORIA NUMBER(10) NOT NULL --Obrigatorio
);

--------------------------------------------------------
--  DDL for Table DHWTB026_FUNC_PERMISSSAO
--------------------------------------------------------
CREATE TABLE DHWTB026_FUNC_PERMISSAO 
(	
	IDEN_FUNCIONALIDADE NUMBER(19), 
	IDEN_PERMISSAO NUMBER(19),
	CONSTRAINT DHWPK026_FUNC_PERMISSAO PRIMARY KEY (IDEN_FUNCIONALIDADE, IDEN_PERMISSAO),
  	CONSTRAINT DHWFK026_DHWTB027_FUNCIONALIDA FOREIGN KEY (IDEN_FUNCIONALIDADE) REFERENCES DHWTB027_FUNCIONALIDADE(IDEN_FUNCIONALIDADE),
  	CONSTRAINT DHWFK026_DHWTB028_PERMISSAO FOREIGN KEY (IDEN_PERMISSAO) REFERENCES DHWTB028_PERMISSAO(IDEN_PERMISSAO)
);

CREATE TABLE DHWTB026_FUNC_PERMISSAO_AUD 
(	
	IDEN_FUNCIONALIDADE NUMBER(19), 
	IDEN_PERMISSAO NUMBER(19),
	TIPO_OPERACAO NUMBER(3), --Obrigatorio
  	IDEN_AUDITORIA NUMBER(10) NOT NULL --Obrigatorio
);

--------------------------------------------------------
--DDL FOR TABLE DHWTB999_AUDITORIA
--------------------------------------------------------
CREATE SEQUENCE DHWSQ999_AUDITORIA NOCACHE;

CREATE TABLE DHWTB999_AUDITORIA 
(
	IDEN_AUDITORIA NUMBER(19), 
	CODG_USUARIO_CEPRO_SECURITY NUMBER(19), 
	DATA_OPERACAO TIMESTAMP (6), 
	ENDR_IP VARCHAR2(39), 
	NOME_USUARIO_RESPONSAVEL VARCHAR2(255), 
	NUMR_CPF_USUARIO_RESPONSAVEL VARCHAR2(11),
	CONSTRAINT DHWPK999_AUDITORIA PRIMARY KEY (IDEN_AUDITORIA)
);

--------------------------------------------------------
--DDL FOR TABLE DHWTB999_AUDITORIA_TABELAS
--------------------------------------------------------
CREATE TABLE DHWTB999_AUDITORIA_TABELAS 
(	
	IDEN_AUDITORIA NUMBER(19), 
	ENTITY_NAME VARCHAR2(255),
	CONSTRAINT DHWPK999_AUDITORIA_TABELAS FOREIGN KEY (IDEN_AUDITORIA) REFERENCES DHWTB999_AUDITORIA(IDEN_AUDITORIA)
);