DROP SEQUENCE DHWSQ027_FUNCIONALIDADE;
CREATE SEQUENCE DHWSQ027_FUNCIONALIDADE NOCACHE;
--USUARIO
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Incluir Usuario','ROLE_INCLUIR_USUARIO','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Consultar Usuario','ROLE_CONSULTAR_USUARIO','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Alterar Usuario','ROLE_ALTERAR_USUARIO','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Excluir Usuario','ROLE_EXCLUIR_USUARIO','ATIVO');
--FIM_USUARIO

--PERFIL
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Incluir Perfil','ROLE_INCLUIR_PERFIL','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Consultar Perfil','ROLE_CONSULTAR_PERFIL','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Alterar Perfil','ROLE_ALTERAR_PERFIL','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Excluir Perfil','ROLE_EXCLUIR_PERFIL','ATIVO');
--FIM_PERFIL

--FUNCIONALIDADE
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Incluir Funcionalidade','ROLE_INCLUIR_FUNCIONALIDADE','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Consultar Funcionalidade','ROLE_CONSULTAR_FUNCIONALIDADE','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Alterar Funcionalidade','ROLE_ALTERAR_FUNCIONALIDADE','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Excluir Funcionalidade','ROLE_EXCLUIR_FUNCIONALIDADE','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Vincular Permissão','ROLE_VINCULAR_FUNCIONALIDADE','ATIVO');
--FIM_FUNCIONALIDADE

--CNAE
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Incluir CNAE','ROLE_INCLUIR_CNAE','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Consultar CNAE','ROLE_CONSULTAR_CNAE','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Alterar CNAE','ROLE_ALTERAR_CNAE','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Excluir CNAE','ROLE_EXCLUIR_CNAE','ATIVO');
--FIM_CNAE

--NATUREZA_JURIDICA
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Incluir Natureza Juridica','ROLE_INCLUIR_NATUREZA_JURIDICA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Consultar Natureza Juridica','ROLE_CONSULTAR_NATUREZA_JURIDICA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Alterar Natureza Juridica','ROLE_ALTERAR_NATUREZA_JURIDICA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Excluir Natureza Juridica','ROLE_EXCLUIR_NATUREZA_JURIDICA','ATIVO');
--FIM_NATUREZA_JURIDICA

--TIPO_OCORRENCIA
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Incluir Tipo Ocorrencia','ROLE_INCLUIR_TIPO_OCORRENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Consultar Tipo Ocorrencia','ROLE_CONSULTAR_TIPO_OCORRENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Alterar Tipo Ocorrencia','ROLE_ALTERAR_TIPO_OCORRENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Excluir Tipo Ocorrencia','ROLE_EXCLUIR_TIPO_OCORRENCIA','ATIVO');
--FIM_TIPO_OCORRENCIA

--TIPO_ADMINISTRACAO
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Incluir Tipo Administração','ROLE_INCLUIR_TIPO_ADMINISTRACAO','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Consultar Tipo Administração','ROLE_CONSULTAR_TIPO_ADMINISTRACAO','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Alterar Tipo Administração','ROLE_ALTERAR_TIPO_ADMINISTRACAO','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Excluir Tipo Administração','ROLE_EXCLUIR_TIPO_ADMINISTRACAO','ATIVO');
--FIM_TIPO_ADMINISTRACAO

--GRUPO_PENDENCIA
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Incluir Grupo','ROLE_INCLUIR_GRUPO_PENDENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Consultar Grupo','ROLE_CONSULTAR_GRUPO_PENDENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Alterar Grupo','ROLE_ALTERAR_GRUPO_PENDENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Excluir Grupo','ROLE_EXCLUIR_GRUPO_PENDENCIA','ATIVO');
--FIM_GRUPO_PENDENCIA

--SUBGRUPO_PENDENCIA
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Incluir Subgrupo','ROLE_INCLUIR_SUBGRUPO_PENDENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Consultar Subgrupo','ROLE_CONSULTAR_SUBGRUPO_PENDENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Alterar Subgrupo','ROLE_ALTERAR_SUBGRUPO_PENDENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Excluir Subgrupo','ROLE_EXCLUIR_SUBGRUPO_PENDENCIA','ATIVO');
--FIM_SUBGRUPO_PENDENCIA

--TIPO_PENDENCIA
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Incluir Tipo Pendencia','ROLE_INCLUIR_TIPO_PENDENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Consultar Tipo Pendencia','ROLE_CONSULTAR_TIPO_PENDENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Alterar Tipo Pendencia','ROLE_ALTERAR_TIPO_PENDENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Excluir Tipo Pendencia','ROLE_EXCLUIR_TIPO_PENDENCIA','ATIVO');
--FIM_TIPO_PENDENCIA

--UNIDADE_ADMINISTRATIVA
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Incluir Unidade Administrativa','ROLE_INCLUIR_UNIDADE_ADMINISTRATIVA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Consultar Unidade Administrativa','ROLE_CONSULTAR_UNIDADE_ADMINISTRATIVA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Alterar Unidade Administrativa','ROLE_ALTERAR_UNIDADE_ADMINISTRATIVA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Excluir Unidade Administrativa','ROLE_EXCLUIR_UNIDADE_ADMINISTRATIVA','ATIVO');
--FIM_UNIDADE_ADMINISTRATIVA
    
--TIPO_OCORRENCIA
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Incluir Ocorrencia','ROLE_INCLUIR_OCORRENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Consultar Ocorrencia','ROLE_CONSULTAR_OCORRENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Alterar Ocorrencia','ROLE_ALTERAR_OCORRENCIA','ATIVO');
INSERT INTO DHWTB027_FUNCIONALIDADE (IDEN_FUNCIONALIDADE,data_atualizacao,data_criacao,versao,descricao,nome,FLAG_SITUACAO) 
    VALUES (DHWSQ027_FUNCIONALIDADE.nextval,null,sysdate,0,'Excluir Ocorrencia','ROLE_EXCLUIR_OCORRENCIA','ATIVO');
--FIM_TIPO_OCORRENCIA